services:
  - type: web
    name: zigme-blog-client
    runtime: static
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
